### ISSUE TITLE
new ui: projects, run debug buttons 

### ISSUE THREAD

**Issue by xsa-dev** [leizhag/eink-color-scheme#2]
In new UI not all correct.

Issues:
1. in project switch menu hide all projects
![image](https://user-images.githubusercontent.com/16959353/215217460-b03faba1-fc3d-4662-a4c4-244a0b935a31.png)

2. buttons to debug or run hided
![image](https://user-images.githubusercontent.com/16959353/215217330-90e1e3eb-f0ef-4074-ab4a-f18cc0c47203.png)

**Comment by leizhag** [comment]
Thanks for your feedback!

This's a color scheme plugin that does not affect UI elements like buttons, but only changes looking of the editing area.

Can you verify this by disabling the plugin, and see whether the problem goes away?

**Comment by xsa-dev** [comment]
I have updated the IDE, and this issue no longer bothers me.
